package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Monday, 28 April, 2025 8:55:01 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String s);
} // interface ReverseOperations
